FROM node:lts-alpine AS packages
WORKDIR /movinin/packages

COPY ./packages /movinin/packages

# Install dependencies for all internal packages
RUN set -e && \
  find ./ -mindepth 1 -maxdepth 1 -type d \
  -exec sh -c 'for dir; do \
    if [ -f "$dir/package.json" ]; then \
      echo "Installing dependencies in $dir"; \
      npm --prefix "$dir" install; \
    fi; \
  done' _ {} +


FROM node:lts-alpine AS build

WORKDIR /movinin/backend

COPY ./backend/package*.json ./

RUN npm install --force && \
    npm cache clean --force

FROM node:lts-alpine
WORKDIR /movinin/backend

COPY --from=build /movinin/backend/node_modules ./node_modules

COPY --from=packages /movinin/packages /movinin/packages

COPY ./backend ./
COPY ./backend/.env.docker .env

RUN npm run setup

EXPOSE 4004

CMD ["npm", "run", "dev"]
