declare module '@env' {
    export const MI_API_HOST: string
    export const MI_DEFAULT_LANGUAGE: string
    export const MI_PAGE_SIZE: string
    export const MI_PROPERTIES_PAGE_SIZE: string
    export const MI_BOOKINGS_PAGE_SIZE: string
    export const MI_CDN_USERS: string
    export const MI_CDN_PROPERTIES: string
    export const MI_AGENCY_IMAGE_WIDTH: string
    export const MI_AGENCY_IMAGE_HEIGHT: string
    export const MI_PROPERTY_IMAGE_WIDTH: string
    export const MI_PROPERTY_IMAGE_HEIGHT: string
    export const MI_MINIMUM_AGE: string
    export const MI_STRIPE_PUBLISHABLE_KEY: string
    export const MI_STRIPE_MERCHANT_IDENTIFIER: string
    export const MI_STRIPE_COUNTRY_CODE: string
    export const MI_BASE_CURRENCY: string
    export const MI_WEBSITE_NAME: string
}
