import * as movininTypes from 'movinin-types';
export declare function formatNumber(x?: number): string;
export declare function formatDatePart(n: number): string;
export declare function capitalize(str: string): string;
export declare function isDate(date?: Date): boolean;
export declare const joinURL: (part1?: string, part2?: string) => string;
export declare const isInteger: (val: string) => boolean;
export declare const isYear: (val: string) => boolean;
export declare const isCvv: (val: string) => boolean;
export declare const arrayEqual: (a: any, b: any) => boolean;
export declare const clone: (obj: any) => any;
export declare function cloneArray<T>(arr: T[]): T[] | undefined | null;
export declare const filterEqual: (a?: movininTypes.Filter | null, b?: movininTypes.Filter | null) => boolean;
export declare const flattenAgencies: (companies: movininTypes.User[]) => string[];
export declare const days: (from?: Date, to?: Date) => number;
export declare const fr: (user?: movininTypes.User) => boolean;
export declare const extraToNumber: (extra: string) => number;
export declare const extraToString: (extra: number) => string;
export declare const trimCarriageReturn: (str: string) => string;
